services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    networks:
      - app-net

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_USER: system
      ORACLE_PASSWORD: oracle
      ORACLE_DATABASE: user_service
    ports:
      - "0.0.0.0:1521:1521"
    networks:
      - app-net

networks:
  app-net: